### ISSUE TITLE
Clarify JOIN-THREAD / ABNORMAL-EXIT

### ISSUE THREAD

**Issue by phoe** [sionescu/bordeaux-threads#103]
https://github.com/sionescu/bordeaux-threads/blob/07a6999eb922498511af04ff74825bbe462fce8d/docs/content/threads/join-thread.md#L35-L36

What does it mean for a thread to be terminated by a condition in this context? What type of condition is required for that to happen? How does this interact with entering the debugger? What if no conditions are signaled and instead `(invoke-restart (car (last (compute-restarts))))` is evaluated to invoke the bottommost `abort` restart to completely unwind the stack via a non-local exit? How is `abnormal-exit` signaled - since it's a subtype of `error`, is it signaled via `cl:error` and therefore must be handled in order to avoid entering the debugger?

**Comment by sionescu** [comment]
Yes, `abnormal-exit` is signaled using `cl:error` and must be handled.
The code tries to handle the common case where a thread is terminated by an unhandled error, in order to avoid entering the debugger.
That is very useful on a server where you don't want threads to be stuck in the debugger endlessly.

**Comment by phoe** [comment]
Yes, that works. I think this clarification should be a part of the API - the context surrounding this condition is quite important.

There's still a question "what happens when a thread signals no error but instead otherwise unwinds all the way down, e.g. via the `abort` restart" that I think should be clarified in this context.
